# Generated by Django 5.2 on 2025-04-11 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='pics/recipes'),
        ),
    ]
