# Generated by Django 5.2 on 2025-04-12 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0002_recipe_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/recipes'),
        ),
    ]
