# Generated by Django 5.2 on 2025-05-26 23:37

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0003_recipe_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='audio',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True),
        ),
    ]
