# Generated by Django 5.2 on 2025-11-20 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipe', '0004_alter_recipe_audio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='audio',
            field=models.FileField(blank=True, null=True, upload_to='audio/recipes'),
        ),
    ]
